# Generated by Django 4.2 on 2023-04-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, default='<django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=255, unique=True),
        ),
    ]
