# Generated by Django 4.2 on 2023-04-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_house_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
